In [1]:
import pandas as pd
df = pd.read_csv("netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [2]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [3]:
df.shape

(8807, 12)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [8]:
df['country'] = df['country'].fillna("Unknown")

In [10]:
df = df.dropna(subset = ['director'])

In [11]:
df.isnull().sum()

show_id           0
type              0
title             0
director          0
cast            473
country           0
date_added        0
release_year      0
rating            1
duration          3
listed_in         0
description       0
dtype: int64

In [12]:
df= df.drop_duplicates()

In [13]:
df.shape

(6173, 12)

In [14]:
df['cast'] = df['cast'].fillna("Unknown")

In [15]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          1
duration        3
listed_in       0
description     0
dtype: int64

In [16]:
df['title'].head()

0                Dick Johnson Is Dead
2                           Ganglands
5                       Midnight Mass
6    My Little Pony: A New Generation
7                             Sankofa
Name: title, dtype: object

In [17]:
df[['title','country','release_year']].head()

,title,country,release_year
0,Dick Johnson Is Dead,United States,2020
2,Ganglands,Unknown,2021
5,Midnight Mass,Unknown,2021
6,My Little Pony: A New Generation,Unknown,2021
7,Sankofa,"United States, Ghana, Burkina Faso, United Kin...",1993

In [19]:
df['type'].value_counts()

type
Movie      5943
TV Show     230
Name: count, dtype: int64

In [21]:
df['country'].value_counts().head(10)

country
United States     2048
India              890
Unknown            422
United Kingdom     212
Canada             119
Spain              106
Egypt               90
Nigeria             90
Japan               85
France              81
Name: count, dtype: int64

In [22]:
df['rating'].value_counts().head(10)

rating
TV-MA    2117
TV-14    1457
R         795
TV-PG     538
PG-13     489
PG        286
TV-Y7     132
TV-G      118
TV-Y      112
NR         75
Name: count, dtype: int64

In [23]:
df['listed_in'].value_counts().head(10)

listed_in
Dramas, International Movies                        361
Documentaries                                       334
Stand-Up Comedy                                     309
Comedies, Dramas, International Movies              271
Dramas, Independent Movies, International Movies    252
Children & Family Movies, Comedies                  196
Children & Family Movies                            193
Documentaries, International Movies                 179
Dramas, International Movies, Romantic Movies       174
Comedies, International Movies                      173
Name: count, dtype: int64

In [24]:
df.sort_values(by = 'release_year', ascending = False).head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1050,s1051,Movie,Ride or Die,Ryuichi Hiroki,"Kiko Mizuhara, Honami Sato, Yoko Maki, Anne Su...",Japan,"April 15, 2021",2021,TV-MA,143 min,"Dramas, International Movies, LGBTQ Movies",Rei helps the woman she’s been in love with fo...
771,s772,TV Show,Pretty Guardian Sailor Moon Eternal The Movie,Chiaki Kon,"Kotono Mitsuishi, Hisako Kanemoto, Rina Satou,...",Unknown,"June 3, 2021",2021,TV-14,1 Season,TV Shows,When a dark power enshrouds the Earth after a ...
1281,s1282,Movie,Red,Tirumala Kishore,"Ram Pothineni, Nivetha Pethuraj, Malvika Sharm...",India,"February 23, 2021",2021,TV-14,143 min,"Dramas, International Movies",A murder investigation leads police to a photo...
377,s378,Movie,Bartkowiak,Daniel Markowicz,"Józef Pawłowski, Zofia Domalik, Szymon Bobrows...",Poland,"July 28, 2021",2021,TV-MA,92 min,"Action & Adventure, International Movies","After his brother dies in a car crash, a disgr..."
375,s376,Movie,Resort to Love,Steven Tsuchida,"Christina Milian, Jay Pharoah, Sinqua Walls, T...",Unknown,"July 29, 2021",2021,TV-14,102 min,"Comedies, Romantic Movies",Reeling from a broken heart and career meltdow...
1280,s1281,Movie,Pelé,"David Tryhorn, Ben Nicholas",Unknown,United Kingdom,"February 23, 2021",2021,TV-14,109 min,"Documentaries, International Movies, Sports Mo...",Against the backdrop of a turbulent era in Bra...
373,s374,Movie,The Last Mercenary,David Charhon,"Jean-Claude Van Damme, Alban Ivanov, Éric Judo...",Unknown,"July 30, 2021",2021,TV-MA,112 min,"Action & Adventure, Comedies, International Mo...",A legendary secret agent-turned-mercenary come...
372,s373,Movie,Rurouni Kenshin: The Beginning,Keishi Otomo,"Takeru Satoh, Kasumi Arimura, Issey Takahashi,...",Unknown,"July 30, 2021",2021,TV-MA,138 min,"Action & Adventure, International Movies","Before he was a protector, Kenshin was a fears..."
1278,s1279,Movie,Brian Regan: On the Rocks,Troy Miller,Brian Regan,United States,"February 23, 2021",2021,TV-G,58 min,Stand-Up Comedy,Brian Regan tackles the big issues weighing on...
363,s364,Movie,The Vault,Jaume Balagueró,"Freddie Highmore, Astrid Bergès-Frisbey, Sam R...",Unknown,"July 31, 2021",2021,R,118 min,"Action & Adventure, International Movies, Thri...",A genius engineer and his crew of amateur thie...

In [25]:
df.sort_values(by = 'title').head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2036,s2037,Movie,#Alive,Cho Il,"Yoo Ah-in, Park Shin-hye",South Korea,"September 8, 2020",2020,TV-MA,99 min,"Horror Movies, International Movies, Thrillers","As a grisly virus rampages a city, a lone man ..."
2304,s2305,Movie,#AnneFrank - Parallel Stories,"Sabina Fedeli, Anna Migotto","Helen Mirren, Gengher Gatti",Italy,"July 1, 2020",2019,TV-14,95 min,"Documentaries, International Movies","Through her diary, Anne Frank's story is retol..."
2481,s2482,Movie,#FriendButMarried,Rako Prijanto,"Adipati Dolken, Vanesha Prescilla, Rendi Jhon,...",Indonesia,"May 21, 2020",2018,TV-G,102 min,"Dramas, International Movies, Romantic Movies","Pining for his high school crush for years, a ..."
2324,s2325,Movie,#FriendButMarried 2,Rako Prijanto,"Adipati Dolken, Mawar de Jongh, Sari Nila, Von...",Indonesia,"June 28, 2020",2020,TV-G,104 min,"Dramas, International Movies, Romantic Movies",As Ayu and Ditto finally transition from best ...
5973,s5974,Movie,#Roxy,Michael Kennedy,"Jake Short, Sarah Fisher, Booboo Stewart, Dann...",Canada,"April 10, 2019",2018,TV-14,105 min,"Comedies, Romantic Movies",A teenage hacker with a huge nose helps a cool...
5695,s5696,Movie,#Rucker50,Robert McCullough Jr.,Unknown,United States,"December 1, 2016",2016,TV-PG,56 min,"Documentaries, Sports Movies",This documentary celebrates the 50th anniversa...
654,s655,Movie,#Selfie,Cristina Jacob,"Flavia Hojda, Crina Semciuc, Olimpia Melinte, ...",Romania,"June 21, 2021",2014,TV-MA,125 min,"Comedies, Dramas, International Movies","Two days before their final exams, three teen ..."
655,s656,Movie,#Selfie 69,Cristina Jacob,"Maia Morgenstern, Olimpia Melinte, Crina Semci...",Romania,"June 21, 2021",2016,TV-MA,119 min,"Comedies, Dramas, International Movies","After a painful breakup, a trio of party-lovin..."
5972,s5973,Movie,#cats_the_mewvie,Michael Margolis,Unknown,Canada,"February 5, 2020",2020,TV-14,90 min,"Documentaries, International Movies",This pawesome documentary explores how our fel...
5277,s5278,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [51]:
df[(df['type']=='Movie') & (df['release_year']> 2015) & (df['country'].str.contains("India", na=False))].head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
105,s106,Movie,Angamaly Diaries,Lijo Jose Pellissery,"Antony Varghese, Reshma Rajan, Binny Rinky Ben...",India,"September 5, 2021",2017,TV-14,128 min,"Action & Adventure, Comedies, Dramas",After growing up amidst the gang wars of his h...
118,s119,Movie,Gurgaon,Shanker Raman,"Akshay Oberoi, Pankaj Tripathi, Ragini Khanna,...",India,"September 2, 2021",2017,TV-14,106 min,"Dramas, International Movies, Thrillers",When the daughter of a wealthy family returns ...
126,s127,Movie,Shikara,Vidhu Vinod Chopra,"Aadil Khan, Sadia Khateeb, Zain Khan Durrani, ...",India,"September 2, 2021",2020,TV-14,115 min,"Dramas, International Movies, Romantic Movies",A couple must strive to remain resilient after...
190,s191,Movie,Thimmarusu,Sharan Koppisetty,"Satya Dev, Priyanka Jawalkar, Brahmaji",India,"August 28, 2021",2021,TV-14,125 min,"Dramas, International Movies",Eight years after a young man is framed for mu...
203,s204,Movie,Kyaa Kool Hain Hum 3,Umesh Ghadge,"Tusshar Kapoor, Aftab Shivdasani, Krishna Abhi...",India,"August 27, 2021",2016,TV-MA,124 min,"Comedies, International Movies",When an unlikely porn actor falls for a woman ...

In [34]:
df.groupby('country')['title'].count().sort_values(ascending=False).head(10)

country
United States     2048
India              890
Unknown            422
United Kingdom     212
Canada             119
Spain              106
Nigeria             90
Egypt               90
Japan               85
France              81
Name: title, dtype: int64

In [35]:
df.groupby('type')['title'].count()

type
Movie      5943
TV Show     230
Name: title, dtype: int64

In [36]:
df.groupby('release_year')['title'].count().sort_values(ascending=False).head(10)

release_year
2017    773
2018    760
2016    653
2019    629
2020    548
2015    400
2021    297
2014    267
2013    225
2012    175
Name: title, dtype: int64

In [37]:
df.groupby('director')['title'].count().sort_values(ascending=False).head(10)

director
Rajiv Chilaka             19
Raúl Campos, Jan Suter    18
Suhas Kadav               16
Marcus Raboy              16
Jay Karas                 14
Cathy Garcia-Molina       13
Jay Chapman               12
Youssef Chahine           12
Martin Scorsese           12
Steven Spielberg          11
Name: title, dtype: int64

In [38]:
df.groupby('country').agg({
'title': 'count',
'release_year': ['min', 'max']   
}).sort_values(('title','count'), ascending = False).head(10)

               title release_year
               count          min   max
country
United States   2048         1942  2021
India            890         1959  2021
Unknown          422         1960  2021
United Kingdom   212         1975  2021
Canada           119         1998  2020
Spain            106         2008  2021
Nigeria           90         2003  2021
Egypt             90         1954  2020
Japan             85         1979  2021
France            81         1974  2021

In [45]:
df.groupby('rating').agg({
'title': 'count',
'type':'nunique'  
}).sort_values('title', ascending = False)

          title  type
rating
TV-MA      2117     2
TV-14      1457     2
R           795     2
TV-PG       538     2
PG-13       489     1
PG          286     1
TV-Y7       132     2
TV-G        118     2
TV-Y        112     2
NR           75     1
G            41     1
TV-Y7-FV      4     1
UR            3     1
NC-17         2     1
74 min        1     1
84 min        1     1
66 min        1     1

In [47]:
df.groupby(['release_year', 'type'])['title'].count().head(20)

release_year  type
1942          Movie      2
1943          Movie      3
1944          Movie      3
1945          Movie      3
1946          Movie      1
              TV Show    1
1947          Movie      1
1954          Movie      2
1955          Movie      3
1956          Movie      2
1958          Movie      3
1959          Movie      1
1960          Movie      4
1961          Movie      1
1962          Movie      3
1963          Movie      1
1964          Movie      2
1965          Movie      2
1966          Movie      1
1967          Movie      4
Name: title, dtype: int64

In [50]:
df.groupby('type')['release_year'].agg([
'min', 'max', 'mean'  
])

          min   max         mean
type
Movie    1942  2021  2013.010601
TV Show  1946  2021  2017.573913